export const INIT_INGREDIENT = 'INIT_INGREDIENT';
export const ADD_INGREDIENT = 'ADD_INGREDIENT';
export const REMOVE_INGREDIENT = 'REMOVE_INGREDIENT';
export const UPDATE_PURCHASEABLE = 'UPDATE_PURCHASEABLE';